function generateMTL(picnums: number[]): string {
  const lines = ["# Material Library", "# Generated by Build Map Exporter", ""];

  for (const picnum of picnums) {
    lines.push(
      `newmtl texture_${picnum}`,
      "Ka 1.000 1.000 1.000",
      "Kd 1.000 1.000 1.000",
      "Ks 0.000 0.000 0.000",
      "Ns 0.000",
      "d 1.000",
      "illum 1",
      `map_Kd texture_${picnum}.png`,
      `map_d texture_${picnum}.png`,
      "",
    );
  }

  return lines.join("\n");
}

export { generateMTL };
